/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 macbook.gltf --transform 
Files: macbook.gltf [3.29MB] > macbook.glb [173.37KB] (95%)
Author: KangaroOz 3D (https://sketchfab.com/KangaroOz-3D)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-2021-37763335f74b497e91906986b170b5d1
Title: MacBook Pro 2021
*/

import { useGLTF } from '@react-three/drei'
import { GroupProps } from '@react-three/fiber'
import React from 'react'

export default function Macbook(props: GroupProps) {
  // @ts-expect-error types wrong
  const { nodes, materials } = useGLTF('/3d-models/macbook.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.MacBookPro}
      />
    </group>
  )
}

useGLTF.preload('/3d-models/macbook.glb')
